[package]
name = "l_rsa"
version = "0.4.0"
edition = "2021"
description = "Extendable tool for analyzing RSA Attacks based on public keys."
authors = ["Luatic"]
repository = "https://github.com/DLLuatic/l_rsa/"
license-file = "LICENSE"

[dependencies]
